/** Auto-generated by `npm run port:loading-ui` */
"use client";

import { AnalyzingImage } from "../../../src/loading-ui/analyzing-image";
import { Arc } from "../../../src/loading-ui/arc";
import { Bars } from "../../../src/loading-ui/bars";
import { BobbingDots } from "../../../src/loading-ui/bobbing-dots";
import { BouncingDots } from "../../../src/loading-ui/bouncing-dots";
import { Classic } from "../../../src/loading-ui/classic";
import { ClockRing } from "../../../src/loading-ui/clock-ring";
import { CometSpinner } from "../../../src/loading-ui/comet-spinner";
import { ConcentricRing } from "../../../src/loading-ui/concentric-ring";
import { DashRing } from "../../../src/loading-ui/dash-ring";
import { DotsRing } from "../../../src/loading-ui/dots-ring";
import { Dots } from "../../../src/loading-ui/dots";
import { DualArc } from "../../../src/loading-ui/dual-arc";
import { InfinityLoop } from "../../../src/loading-ui/infinity";
import { OrbitRing } from "../../../src/loading-ui/orbit-ring";
import { PulsatingDots } from "../../../src/loading-ui/pulsating-dots";
import { PulseDot } from "../../../src/loading-ui/pulse-dot";
import { Pulse } from "../../../src/loading-ui/pulse";
import { QuarterRing } from "../../../src/loading-ui/quarter-ring";
import { Ring } from "../../../src/loading-ui/ring";
import { Ripple } from "../../../src/loading-ui/ripple";
import { SatelliteRing } from "../../../src/loading-ui/satellite-ring";
import { Skeleton } from "../../../src/loading-ui/skeleton";
import { Spiral } from "../../../src/loading-ui/spiral";
import { Spokes } from "../../../src/loading-ui/spokes";
import { Swirling } from "../../../src/loading-ui/swirling";
import { Terminal } from "../../../src/loading-ui/terminal";
import { TextBlink } from "../../../src/loading-ui/text-blink";
import { TextDots } from "../../../src/loading-ui/text-dots";
import { TextShimmerWave } from "../../../src/loading-ui/text-shimmer-wave";
import { TextShimmer } from "../../../src/loading-ui/text-shimmer";
import { TripleDotSpinner } from "../../../src/loading-ui/triple-dot-spinner";
import { TwinOrbit } from "../../../src/loading-ui/twin-orbit";
import { Typing } from "../../../src/loading-ui/typing";
import { WanderingEyes } from "../../../src/loading-ui/wandering-eyes";
import { Wave } from "../../../src/loading-ui/wave";

import type { ComponentType } from "react";

/** Heterogeneous loader props — use `any` so the overview grid can hold every registry export. */
export const LOADING_UI_KIT_TILES: readonly [string, ComponentType<any>][] = [
  ["analyzing-image", AnalyzingImage],
  ["arc", Arc],
  ["bars", Bars],
  ["bobbing-dots", BobbingDots],
  ["bouncing-dots", BouncingDots],
  ["classic", Classic],
  ["clock-ring", ClockRing],
  ["comet-spinner", CometSpinner],
  ["concentric-ring", ConcentricRing],
  ["dash-ring", DashRing],
  ["dots-ring", DotsRing],
  ["dots", Dots],
  ["dual-arc", DualArc],
  ["infinity", InfinityLoop],
  ["orbit-ring", OrbitRing],
  ["pulsating-dots", PulsatingDots],
  ["pulse-dot", PulseDot],
  ["pulse", Pulse],
  ["quarter-ring", QuarterRing],
  ["ring", Ring],
  ["ripple", Ripple],
  ["satellite-ring", SatelliteRing],
  ["skeleton", Skeleton],
  ["spiral", Spiral],
  ["spokes", Spokes],
  ["swirling", Swirling],
  ["terminal", Terminal],
  ["text-blink", TextBlink],
  ["text-dots", TextDots],
  ["text-shimmer-wave", TextShimmerWave],
  ["text-shimmer", TextShimmer],
  ["triple-dot-spinner", TripleDotSpinner],
  ["twin-orbit", TwinOrbit],
  ["typing", Typing],
  ["wandering-eyes", WanderingEyes],
  ["wave", Wave],
] as const;
